### ISSUE TITLE
please ship the system conf in the ntpd crate

### ISSUE THREAD

**Issue by sylvestre** [pendulum-project/ntpd-rs#1041]
The crate:
https://crates.io/crates/ntpd
doesn't ship with the systemd configuration: 
https://github.com/pendulum-project/ntpd-rs/blob/main/docs/examples/run-as-service.md

(which should probably be a file)

**Comment by sylvestre** [comment]
@rnijveld can we have a new release soon with this ? :) thanks

**Comment by rnijveld** [comment]
@sylvestre We just released a `1.0.0-rc.1`, and expect a final 1.0.0 release somewhere in the coming one or two weeks!
