### ISSUE TITLE
Metric improvements

### ISSUE THREAD

**Issue by paulgear** [pendulum-project/ntpd-rs#1084]
This is a request to add some additional metrics and labels.

1. ntpd-rs uptime - useful for auto-annotating restarts of the daemon with grafana
2. Build/release info like ntpd-rs version, rust version, build date - this is also for the purpose of auto-annotating events (in this case, upgrades of ntpd-rs.  These could potentially be labels on the above metric or on a new one specifically defined for this, like prometheus-node-exporter does for `node_uname_info` and similar.  (Maybe adding kernel & os-release info for those who aren't also running prometheus-node-exporter might also be useful.)
3. It would also be great if there were a way to configure ntpd-rs not to report selected metrics until it has been running for a number of polls or a certain amount of time, in order to avoid graphs like this, where a system reboot causes peer offsets, delays, and uncertainties to render all of the other graph data invisible.  (I would be happy with an option to disable all metrics except uptime until 6 or 8 polls are complete.)
![image](https://github.com/pendulum-project/ntpd-rs/assets/107222/0a56c4b5-56e2-47b5-960d-7f06a981e4df)

**Comment by rnijveld** [comment]
Adding something like uptime seems like a good idea and should be relatively easy to do and also might be the good metric to expose some version information labels etc on. 

As for the third point, I think we'd prefer not to build anything into ntpd-rs itself, given how much it depends on your use case on whether or not you're interested in the startup values. We'd rather just give you the raw data so you can work with it however you like. Would setting a logarithmic axis scale (or symlog for the offset, with a threshold of 0.001 or similar depending on your use case) work for you? Alternatively, once we have the uptime, you could effectively combine the two metrics to ignore however much you'd like (something like `ntp_source_offset_seconds and ntp_uptime_seconds > 10` should work). Another option would be to set a hard value for max and min, letting the graph line exit the visible portion of the graph whenever it exceeds those. I hope any of those, or a combination works for you. Let me know!

**Comment by paulgear** [comment]
Yeah, makes sense - the startup metrics could definitely be of use when troubleshooting some more esoteric problems.  I'll look into options for handling on the graph side of things.

**Comment by paulgear** [comment]
For what it's worth, logarithmic and symlog are a bit less than useful for peer offsets:
![image](https://github.com/pendulum-project/ntpd-rs/assets/107222/3bedc4ca-bcc7-4c94-a29e-af52a263a8d6)
![image](https://github.com/pendulum-project/ntpd-rs/assets/107222/907d6cb6-ce59-41d5-97a1-a2400331e078)
![image](https://github.com/pendulum-project/ntpd-rs/assets/107222/066e1c3e-52c1-423c-982e-c2f8b614a003)

**Comment by rnijveld** [comment]
I've tried this myself on our own instance. For the offset, symlog should work fine as long as you set the linear threshold to something like 0.01 or 0.001. The default threshold is set to 1, meaning that only offset bigger than 1 second would be shown with the linear scale, which would already make most regular offsets completely hidden. I guess this is something we could include in our docs just for good measure.

**Comment by paulgear** [comment]
I played around with different thresholds for symlog and couldn't find one that worked well with both normal operation and restarts.  I think I'll just stick with linear at the moment, and hope that restarts are relatively infrequent.

**Comment by paulgear** [comment]
Also, thanks very much @rnijveld and @davidv1992 for your prompt responses!  I now have lovely automatic restart markers showing me version upgrades!
![image](https://github.com/pendulum-project/ntpd-rs/assets/107222/7f4408df-cb39-41d1-8eb5-99dbc8362020)
