### ISSUE TITLE
server-only mode (allow having no sources configured)

### ISSUE THREAD

**Issue by tq-steina** [pendulum-project/ntpd-rs#1113]
Currently I have to configure a `[[source]]` section defining the time source. While this is sensible if the ntpd (NTP client) is intented to keep system time correct.

In my usecase I rather use the ntdp server for my development machines on a different non-public subnet. This is just for serving the time in case RTC was disconnected from backup voltage.

I workaround this by using myself as a peer with this config snippet:
```
[[source]]
mode = "server"
address = "localhost"
```
But this spams the log with info messages: `INFO ntp_proto::peer: Peer rejected due to invalid stratum. The stratum of a peer must be lower than the own stratum peer_stratum=8 own_stratum=8` which is correct by itself, but to be expect in my case.

Is there a chance to implement server-mode only?

**Comment by davidv1992** [comment]
It already exists. You can get the server to act as a stratum-1 server by setting in the configuration
```
[synchronization]
local-stratum = 1
```

**Comment by tq-steina** [comment]
If the server is configured either as stratum-1 or stratum-8 doesn't make any difference, I still need to configure a peer in `[[source]]`.

This is the configuration I tried:
```
[observability]
# Other values include trace, debug, warn and error
log-level = "info"
observation-path = "/var/run/ntpd-rs/observe"

#[[source]]
#mode = "server"
#address = "localhost"

[[server]]
listen = "[::]:123"

[synchronization]
local-stratum = 1
```
resulting in the following error:
```
Okt 05 13:35:31 steina-w systemd[1]: Started Rust Network Time Service.
Okt 05 13:35:31 steina-w ntp-daemon[3929646]: There was an error loading the config: config toml parsing error: TOML parse error at line 1, column 1
Okt 05 13:35:31 steina-w ntp-daemon[3929646]:   |
Okt 05 13:35:31 steina-w ntp-daemon[3929646]: 1 | [observability]
Okt 05 13:35:31 steina-w ntp-daemon[3929646]:   | ^
Okt 05 13:35:31 steina-w ntp-daemon[3929646]: missing field `source`
Okt 05 13:35:31 steina-w systemd[1]: ntpd-rs.service: Main process exited, code=exited, status=78/CONFIG
Okt 05 13:35:31 steina-w systemd[1]: ntpd-rs.service: Failed with result 'exit-code'.
```

**Comment by rnijveld** [comment]
You can work around this by adding `source = []` at the top of your configuration (above the `[observability]` header). That should be the default though, so you shouldn't have to configure it. I'll re-open this issue to track that.

**Comment by tq-steina** [comment]
Nice, thanks. This does the trick. For completeness my config:
```
source = []

[observability]
# Other values include trace, debug, warn and error
log-level = "info"
observation-path = "/var/run/ntpd-rs/observe"

[[server]]
listen = "[::]:123"

[synchronization]
local-stratum = 8
```
I still get these two warnings:
```
Okt 05 13:46:14 steina-w ntp-daemon[55195]: 2023-10-05T11:46:14.377667Z  WARN ntpd::daemon::config: No sources configured. Daemon will not change system time.
Okt 05 13:46:14 steina-w ntp-daemon[55195]: 2023-10-05T11:46:14.377696Z  WARN ntpd::daemon::config: Fewer sources configured than are required to agree on the current time. Daemon will not change system time.
```
Which doesn't take the intented configuration into account, but is okay for me (now)
