### ISSUE TITLE
Implement NTPv5

### ISSUE THREAD

**Issue by cikzh** [pendulum-project/ntpd-rs#1124]
Spec: https://www.ietf.org/id/draft-ietf-ntp-ntpv5-00.html

- [x] Write tests based on encoded v5 packets
- [x] Implement v5 header parsing
- [x] Write tests for draft identification extension field
- [x] Implement draft identification extension field
- [x] Implement v5 server packet handling
- [x] Write v5 server tests
- [x] Create negotiation protocol tests
- [x] Implement negotiation protocol
- [x] Add peer tests for v5 sending
- [x] Add peer tests for v5 response parsing
- [x] Implement v5 handling in peer

Optional/Notes:
- [ ] Implement Extensions
  - [x] Draft Identification
  - [ ] Padding
  - [ ] MAC
  - [ ] Reference ID
  - [ ] Server Information
  - [ ] Correction
  - [ ] Reference Timestamp
  - [ ] Monotonic Receive Timestamp
  - [ ] Secondary Receive Timestamp

**Comment by tdittr** [comment]
Started work in #1125

**Comment by davidv1992** [comment]
Missing a step for V5 extension field parsing (note that this format is different from v4!)

**Comment by tdittr** [comment]
> Missing a step for V5 extension field parsing (note that this format is different from v4!)

But if I understand the draft correctly all NTPv4 extensions are valid NTPv5 extensions right? The only difference seems to be that NTPv5 allows extensions with size 4 (no data, only type and length).

From the draft:
> Extension fields specified for NTPv4 can be included in NTPv5 messages as specified for NTPv4.

**Comment by davidv1992** [comment]
yes, all ntpv4 extensions are valid for ntpv5. However, the format for the extension field header (specifically the interpretation of the size field) has changed. In ntpv4 the size is that of the entire extension field including header and padding. In ntpv4 it is the size of the extensionfield excluding padding (and maybe the header? not sure on that).

**Comment by tdittr** [comment]
> yes, all ntpv4 extensions are valid for ntpv5. However, the format for the extension field header (specifically the interpretation of the size field) has changed. In ntpv4 the size is that of the entire extension field including header and padding. In ntpv5 it is the size of the extensionfield excluding padding (and maybe the header? not sure on that).

Oh I see, that is not very clear from the spec, it only says:
> If the length is not divisible by 4, the extension field is padded with zeros to the smallest multiple of 4 octets.

Which is not very explicit.

Also it is not clear if NTPv4 extensions will set the length field by the old or by the new way of counting.

**Comment by tdittr** [comment]
Implementation for use in peer is being worked on on #1143
