### ISSUE TITLE
please publish ntp-metrics-exporter - 1.0.0 on crates.io

### ISSUE THREAD

**Issue by sylvestre** [pendulum-project/ntpd-rs#1148]
https://crates.io/crates/ntp-metrics-exporter/dependencies
points to version 0.3.7 of other ntp crates

**Comment by rnijveld** [comment]
The ntp-metrics-exporter crate is no longer part of ntpd-rs (same with ntp-ctl and ntp-daemon). Instead the ntp-ctl, ntp-daemon and ntp-metrics-exporter binaries that were in those crates are exposed directly in the ntpd crate.

**Comment by sylvestre** [comment]
OK, thanks :)
Maybe remove the crate from crates.io ?

**Comment by rnijveld** [comment]
Unfortunately crates.io does not allow easy removal of crates, we could try and contact the admins of crates.io, but they appear to be hesitant to remove crates. I think we could yank all published versions though, to at least prevent any new installs from the old packages.
