### ISSUE TITLE
openSUSE packaging

### ISSUE THREAD

**Issue by cikzh** [pendulum-project/ntpd-rs#1237]
Try setting up packaging for openSUSE:

https://en.opensuse.org/openSUSE:Packaging_Rust_Software

**Comment by udf2457** [comment]
Ping #1086

**Comment by mnhauke** [comment]
I just made a package for openSUSE ...
https://build.opensuse.org/package/show/network:time/ntpd-rs

The  package is also on it's way to openSUSE Factory where all (open)SUSE distributions are branched from
https://build.opensuse.org/request/show/1168654

**Comment by Firstyear** [comment]
Looks like it's already been accepted into factory, great work! https://build.opensuse.org/package/show/openSUSE:Factory/ntpd-rs

**Comment by Firstyear** [comment]
And I want to say, I just installed and setup this up in less than 5 minutes. Exceptional work from the whole project and all it's contributors!
