### ISSUE TITLE
Algorithm paper not linked from docs site

### ISSUE THREAD

**Issue by mcpherrinm** [pendulum-project/ntpd-rs#1518]
The docs/algorithm paper contains many interesting details on ntpd-rs's implementation of ntp, but isn't linked from the documentation site, so it is hard to discover.

It would be helpful if it was linked from that page (or inlined into the content, but I assume getting latex onto the web would be extra work)

**Comment by cikzh** [comment]
A link to the paper is now added to the documentation website. See https://github.com/pendulum-project/ntpd-rs/pull/1717
