### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by cikzh** [pendulum-project/ntpd-rs#1596]
Given the feedback by @mcpherrinm and @Bradatletsencrypt, we should improve on our log messages.

Example improvements:
- Demote noisy logs such as the Kalman filter status to Debug level
- More logs around the status of a source -> Info level message when a source becomes usable, Warning level message when it turns unusable

**Comment by mcpherrinm** [comment]
Just following up here because I had some logs open:


This doesn't tell me which source is being rejected:
```
Aug 26 20:56:58 a ntp-daemon[149767]: 2024-08-26T20:56:58.280916Z  INFO ntp_proto::source: Source rejected due to invalid stratum. The stratum of a source must be lower than the own stratum source_stratum=16 own_stratum=16
```

This seems like it should be debug level:
```
Aug 26 20:55:16 a ntp-daemon[149767]: 2024-08-26T20:55:16.599388Z  INFO ntp_proto::algorithm::kalman: Offset: 0.18890412122828545+-0.18347693260053594ms, frequency: 0.27974997666258733+-1.395606428300284ppm
Aug 26 20:55:16 a ntp-daemon[149767]: 2024-08-26T20:55:16.599422Z  INFO ntp_proto::algorithm::kalman: Changed frequency, current steer 0.27974997673929636ppm, desired freq 0ppm
```

**Comment by mcpherrinm** [comment]
```Aug 27 22:26:39 vm ntp-daemon[118563]: 2024-08-27T22:26:39.847784Z  INFO spawn{index=SourceId(3593) name="time.nist.gov:123" source_addr=128.138.140.44:123 interface=None timestamp_mode=KernelAll source=NtpSource { nts: None, last_poll_interval: PollInterval(16 s), remote_min_poll_interval: PollInterval(16 s), current_request_identifier: None, stratum: 16, reference_id: ReferenceId(1481527118), source_addr: 128.138.140.44:123, source_id: ReferenceId(2156563500), reach: Reach(unreachable), tries: 0, controller: KalmanSourceController { index: SourceId(3593), state: SourceState(Initial(InitialSourceFilter { roundtriptime_stats: AveragingBuffer { data: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], next_idx: 0 }, init_offset: AveragingBuffer { data: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], next_idx: 0 }, last_measurement: None, samples: 0 })), algo_config: AlgorithmConfig { precision_low_probability: 0.3333333333333333, precision_high_probability: 0.6666666666666666, precision_hysteresis: 16, precision_minimum_weight: 0.1, poll_interval_low_weight: 0.4, poll_interval_high_weight: 0.6, poll_interval_hysteresis: 16, poll_interval_step_threshold: 1e-6, delay_outlier_threshold: 5.0, initial_wander: 1e-8, initial_frequency_uncertainty: 0.0001, maximum_source_uncertainty: 0.25, range_statistical_weight: 2.0, range_delay_weight: 0.25, steer_offset_threshold: 2.0, steer_offset_leftover: 1.0, steer_frequency_threshold: 0.0, steer_frequency_leftover: 0.0, step_threshold: 0.01, slew_maximum_frequency_offset: 0.0002, slew_minimum_duration: 8.0, maximum_frequency_steer: 0.000495, ignore_server_dispersion: false, meddling_threshold: NtpDuration(5000.000001164153 ms) }, source_defaults_config: SourceDefaultsConfig { poll_interval_limits: PollIntervalLimits { min: PollInterval(16 s), max: PollInterval(1024 s) }, initial_poll_interval: PollInterval(16 s) } }, source_defaults_config: SourceDefaultsConfig { poll_interval_limits: PollIntervalLimits { min: PollInterval(16 s), max: PollInterval(1024 s) }, initial_poll_interval: PollInterval(16 s) }, buffer: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], protocol_version: V4 } initial_actions=NtpSourceActionIterator { iter: IntoIter([SetTimer(0ns)]) }}:handle_incoming{[28, 1, 13, 227, 0, 0, 0, 16, 0, 0, 0, 32, 78, 73, 83, 84, 234, 120, 209, 0, 0, 0, 0, 0, 211, 157, 44, 181, 38, 246, 24, 124, 234, 120, 209, 31, 211, 202, 204, 254, 234, 120, 209, 31, 211, 202, 240, 70] local_clock_time=NtpInstant { instant: Instant { tv_sec: 173413, tv_nsec: 196046997 } } send_time=NtpTimestamp(16895483936615027267) recv_time=NtpTimestamp(16895483936795386177) source=ReferenceId(2156563500)}: ntp_proto::algorithm::kalman::source: Increased poll interval interval=PollInterval(128 s)```

This log is excessively long and unhelpful (what's the buffer?)

**Comment by davidv1992** [comment]
For future reference for ourselves, the explicit example at the end is fixed on main.
