### ISSUE TITLE
Limit tokio to current thread

### ISSUE THREAD

**Issue by Firstyear** [pendulum-project/ntpd-rs#1639]
Hi there,

In https://github.com/pendulum-project/ntpd-rs/blob/main/ntpd/bin/ntp-daemon.rs#L5 you are using tokio::main which activates the multi-thread scheduler. On my xeon server with 24 threads, this means that I have ntpd-rs with 24 idle threads. 

I would assume that setting tokio to the current_thread runtime flavour would probably be okay for the project, and also seems like a simpler/less resource consuming default?

**Comment by Firstyear** [comment]
I'd be fine with configurable too, but I would say the default should be single thread as the majority of users of this I assume will be clients. If you're running an ntpd-rs server then it's easy to bump this up if needed.

**Comment by davidv1992** [comment]
We have decided that for now, we make the daemon single threaded if it is not running as a server, and multithreaded otherwise. We feel that this is sufficient for now. Should you really want more flexibility on this please let us know.

**Comment by Firstyear** [comment]
I think that's a good solution, thank you!

**Comment by davidv1992** [comment]
It is not yet included in 1.4.0, but likely will be in the next release (though we don't have a timeline for that yet)
