### ISSUE TITLE
Make sure that the configuration file has correct permissions and warn/error if it does not 

### ISSUE THREAD

**Issue by rnijveld** [pendulum-project/ntpd-rs#518]
We don't want configuration files that have 0o777 permissions

**Comment by 0xcrust** [comment]
Hey. I would like to take this one on. Is that fine with you?

**Comment by davidv1992** [comment]
Feel free to propose a pull request. We do however have some license issues still to discuss internally so it might take a bit to merge it even if it is good (think a few months)

**Comment by 0xcrust** [comment]
Thanks for the heads up. I'd like to make the PR anyways. Some feedback would be appreciated
