### ISSUE TITLE
What's the crates.io entry for this?

### ISSUE THREAD

**Issue by sanmai-NL** [pendulum-project/ntpd-rs#612]
https://crates.io/crates/ntpd appears to be a stale version? https://crates.io/crates/ntpd-rs is something else.

**Comment by sanmai-NL** [comment]
I think the hyperlink to this repo was broken, was it fixed just now or am I confused.

**Comment by sanmai-NL** [comment]
Ah, on docs.rs (went there from crates.io) the hyperlink to this repo is indeed broken.

**Comment by erikjee** [comment]
Right, good catch. We'll fix that when we push new versions, thanks!
