### ISSUE TITLE
Setup a proper security.md file

### ISSUE THREAD

**Issue by davidv1992** [pendulum-project/ntpd-rs#616]
Should make a file with at least:
- Contact email
- When to use security email
- Maybe GPG key?

**Comment by rnijveld** [comment]
I think the SECURITY.md file as we have it right now already pretty much confirms to this, so I think we can close this for now? We could setup a GPG key, but I think we can do that later as well (so we can have a better idea of how to manage it). If people really do not want to use github but would prefer a strong guarantee of a securely sent message, they could for now also just mail me personally by encrypting for the GPG key that I use on github.
