### ISSUE TITLE
Implement zeroize (or something similar) for most/all secrets

### ISSUE THREAD

**Issue by davidv1992** [pendulum-project/ntpd-rs#617]

**Comment by folkertdev** [comment]
partially fixed by #623

**Comment by davidv1992** [comment]
Note: We should at some point still check the rest of the codebase to see if we have covered all relevant secrets

**Comment by davidv1992** [comment]
Checked up on the other potential secrets that we have, and the conclusion is that this is not necessary elsewhere.
