### ISSUE TITLE
Improve threat model

### ISSUE THREAD

**Issue by davidv1992** [pendulum-project/ntpd-rs#618]
Currently missing:
 - Ephemeral state during synchronization requests
 - NTS

**Comment by davidv1992** [comment]
Note: also add reference to https://www.octotrike.org/

**Comment by sanmai-NL** [comment]
The edge labels aren't legible when GitHub is in dark mode.

**Comment by sanmai-NL** [comment]
Please review this source.

Threagile is recommended, but hasn't been maintained for a few years. Next is PyTM. That seems very usable.

**Comment by davidv1992** [comment]
@sanmai-NL Just realized I never properly responded here to your comments, apologies for that. We see this as primarily internal documentation, and can for now live with the limitation around GitHub dark mode.

Around tooling, we are currently not interested in changing methodologies, our current manual process is working for our current development process.
