### ISSUE TITLE
Instant application of the inital step, ntpdate/oneshot mode

### ISSUE THREAD

**Issue by valpackett** [pendulum-project/ntpd-rs#725]
Currently it always takes a couple minutes until we see the first adjustment because adjustments are only applied when there is consensus. However it is often desirable to apply *some* time from the network ASAP, as soon as we have a network. (Imagine a Raspberry Pi-like device without an RTC at all… wouldn't be fun to spend the first few minutes of every boot in 1970! :D)

When there is an option to instantly apply a `clock_settime` from the first remote timestamp we see, it would also be easy to implement an option to quit right after that, to work as an equivalent of the `ntpdate` command. chrony for example has the following options:

```
-q
    When run in this mode, chronyd will set the system clock once and exit. It will not detach from the terminal.
-Q
    This option is similar to the -q option, except it only prints the offset without making any corrections of the clock and it allows chronyd to be started without root privileges.
```

**Comment by sanmai-NL** [comment]
Why would the system clock time be less reliable than a remote clock time? We could reset the system clock to at least the a build timestamp of the ntpd-rs, when the current time is earlier, which would be impossible anyway. Other than that, trusting any non-consensus time could have impact on security.

**Comment by davidv1992** [comment]
Not waiting for consensus would indeed be a bad idea, but I don't think that is necessary to make improvements here. 

Currently the code takes 8 samples of the offset from a server to determine accuracy of the sampling, but this is really only necessary for some statistics to have reasonable initial values and to avoid problems with division by 0. This, combined with the fact that bursting is not yet supported gives the large-ish startup delay.

We could consider returning the measured offset during this period, and just estimating it's inaccuracy as some fixed large value (say 1 second). This wouldn't reduce security and allows the consensus algorithm to find a rough consensus much earlier, fixing problems for machines like the raspberry pi.

**Comment by folkertdev** [comment]
I'll quickly add that I believe Josh Triplett also asked for this feature at the end of [my talk](https://www.youtube.com/watch?v=9Q4yNlbfiYk&t=11300s) at RustNL
