### ISSUE TITLE
Publish rustdoc

### ISSUE THREAD

**Issue by sanmai-NL** [pendulum-project/ntpd-rs#730]
Unless I missed something, the rustdocs for ntpd-rs seem to be unpublished. This is more of a shortcoming than with most other Rust-based OSS products, since producing ntpd-rs‘ rustdoc requires compiling, and compiling requires a specific target environment. In the end, I failed to produce the rustdoc under macOS.

**Comment by cikzh** [comment]
ntpd-rs isn't meant to be used as library at this time, as such we don't currently see a point in making the Rust docs publicly available
