### ISSUE TITLE
Suggestion for systemd file

### ISSUE THREAD

**Issue by mdavids** [pendulum-project/ntpd-rs#732]
https://github.com/pendulum-project/ntpd-rs/blob/c0bc34ca35bd76cad83465a9dd524ad9d6d43074/ntpd-rs.service.example#L16

Should probably contain one extra option, to allow it to start in server mode:

`AmbientCapabilities=CAP_SYS_TIME CAP_NET_BIND_SERVICE`

**Comment by davidv1992** [comment]
I think we shouldn't have this by default, since it is uneccessary for client operation, but I think we should add at least a comment in this example talking about this, see the suggestion in #735

**Comment by mdavids** [comment]
Yep, sounds good. Please be advised that I haven't fully tested this suggestion, because prior to this I did a `sudo setcap CAP_NET_BIND_SERVICE,CAP_SYS_TIME=+eip /usr/bin/ntp-daemon`.

**Comment by davidv1992** [comment]
We do use this ourselves in a few places, this is sufficient and works.
