### ISSUE TITLE
Add support for FreeBSD ports

### ISSUE THREAD

**Issue by kellytk** [pendulum-project/ntpd-rs#740]
With #274 resolved, please consider adding `ntpd-rs` to [ports](https://www.freebsd.org/ports/).

Ports (and its derivative packages) is the preferred method of installing software on FreeBSD and, although I personally write and run Rust-based software on FreeBSD, it would be useful for systems with no Rust toolchain (read: Cargo) present.

https://www.freshports.org/net/chrony/ is an example of an NTP client/server in ports.

**Comment by folkertdev** [comment]
in https://github.com/pendulum-project/ntpd-rs/pull/724 we've been informed that the maintenance of installers in the FreeBSD ecosystem is typically done by the community. We ourselves don't really use FreeBSD in daily life, so it would be both easier for us but also better (in terms of testing and keeping things working with other parts of the ecosystem) if the community picked that up. 

It looks like the chrony entry is maintained by someone other than the main developer of chrony.

**Comment by MikaelUrankar** [comment]
I've pushed https://cgit.freebsd.org/ports/commit/?id=811c1b91629f709da915ab6c9b799e2a7f889923

**Comment by folkertdev** [comment]
@MikaelUrankar that's great!

I'm not familiar with ports. What does it do besides dowloading/building the binaries and putting them in some standard place? Does/could it also handle the installation process? e.g. put the  config in the right place (if yes, where is that?) and configure ntpd-rs as a service (we did some prototyping for that here https://github.com/pendulum-project/ntpd-rs/pull/766)

**Comment by MikaelUrankar** [comment]
The port handles the build and install process.
There are some sample config files (ntp.server.toml and ntp.toml) installed in /usr/local/etc/ntpd-rs.
I've rewritten the rc script: https://github.com/freebsd/freebsd-ports/blob/main/net/ntpd-rs/files/ntp_daemon.in

**Comment by folkertdev** [comment]
Nice, we'll add this to our documentation. We've also moved paths over from `/run` to `/var/run` in the latest pre-release https://github.com/pendulum-project/ntpd-rs/releases/tag/v1.0.0-dev.20230907 so many of your patches will not be needed in the future

**Comment by kellytk** [comment]
[https://www.freshports.org/net/ntpd-rs](https://www.freshports.org/net/ntpd-rs)
`pkg search ntpd-rs`

Thank you @MikaelUrankar, closing.
