### ISSUE TITLE
Config accepted by ntp-daemon but fails explicit validation

### ISSUE THREAD

**Issue by jiripospisil** [pendulum-project/ntpd-rs#822]
Hello, given the following config:

```
[[peers]]
mode = "nts-server"
ke-addr = "time.cloudflare.com:4460"
```

```
ntp-ctl --config /etc/ntpd-rs/ntp.toml validate
```

The command gives no error message but the exit code is `1`. If however I skip this step and just run the daemon with the same config file, it's accepted but the daemon itself gets unhappy.

```
<snip>
ntp_proto::peer: received invalid packet: Failed to decrypt NTS extension fields
```

I'm not sure whether the config file is somehow invalid and the daemon fails because of it, or whether those are two separate issues. Lastly, the [configuration guide](https://github.com/pendulum-project/ntpd-rs/blob/bd413b4f11cc803ead594de46657aaf828e3e224/CONFIGURATION.md) mixes `nts-server` / `server-nts`, and `addr-ke` / `ke-addr`.

**Comment by davidv1992** [comment]
Thanks, have triaged the bug, and we are missing some setup code that causes the warning messages to not be properly output in this case. The message for the configuration is the warning:
```
Fewer peers configured than are required to agree on the current time. Daemon will not change system time.
```

As for the second issue, it seems separate, we will look into it.

**Comment by davidv1992** [comment]
bisect result: commit 1f988a5067f8d60b0775e82c3a47b369379ae0ad causes the failure, need to look into a fix and better tests for this.

**Comment by davidv1992** [comment]
Both issues should be fixed in the newest release, please let us know if you run into further issues.
