### ISSUE TITLE
Have a mechanism to deal with negative time jumps

### ISSUE THREAD

**Issue by rnijveld** [pendulum-project/ntpd-rs#957]
Computers might have there clocks set to a time in the future:

* Sometimes when a computer was shut down (or put in a sleep state) it could have been left in a state where the clock slowly starts to drift forward. If left offline for long enough that can add up and exceed our backward jump threshold (the worst case on my laptop in the past three weeks of running ntpd-rs was a 1800 seconds forward offset that would have been achieved in about 250 days, so most clients probably won't encounter this very often, although having a device unused for half a year or so is not unheard of).
* A user might have manually adjusted the clock to a future time
* A device manufacturer might have delivered the device with a future time

Currently there is no way to get back to a the normal time situation with just ntpd-rs installed on your system unless you adjust your configuration. We could add something like ntpdate to allow one-off corrections to any time to resolve this.

**Comment by mcpherrinm** [comment]
Would #1494 also address this?

**Comment by cikzh** [comment]
This is indeed fixed in #1494
