### ISSUE TITLE
Distribute rendered manpages in releases

### ISSUE THREAD

**Issue by tranzystorek-io** [pendulum-project/ntpd-rs#964]
From a package maintainer's viewpoint, it would be convenient to have a source code release artifact that also includes the pre-generated manpage files.

For distributions like Void lInux, using pandoc is problematic because it can't be built for all target platforms.

**Comment by davidv1992** [comment]
Implementation choice: Add pipeline to release that generates a source zip with manpages.

**Comment by rnijveld** [comment]
Note: 'precompiled' man pages are now included in the repository (in the `docs/precompiled/man` directory), they will need to be regenerated every time a change to the md source files is made, but that is checked with a CI pipeline, so they should always stay in sync.

**Comment by tranzystorek-io** [comment]
Thank you for adding this!
